name: ci
on: [pull_request]



jobs:
  checkout:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["8", "17"]
    steps:
      - uses: actions/checkout@v4
      - run: echo 'código fonte baixado...'

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - run: echo 'setup java com sucesso'
      - run: mvn clean test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: romaogui87/aula:0.0.1