name: ci
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'rodando job 1...'
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo 'rodando job 2...'

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo 'rodando job 3...'



#name: ci
#on: [push]
#jobs:
#    checkout:
#      runs-on: ubuntu-latest
#      steps:
#        - uses: actions/checkout@v4
#        - run: echo 'código fonte baixado...'
#
#        - uses: actions/setup-java@v3
#          with:
#            java-version: '17'
#            distribution: 'temurin'
#            cache: maven
#        - run: echo 'setup java com sucesso'
#        - run: mvn clean test